#!/usr/bin/env python

import argparse, os, subprocess

parser = argparse.ArgumentParser(
        description='''extracts strain, accession, and group information from homolog.faa files generated by PyParanoid''')

# add the parser arguments
parser.add_argument("input_dir", type=str, help="path/to/homolog.faa")
parser.add_argument("output_dir", type=str, help="path/to/output.tsv/")

args=parser.parse_args()

input_path = args.input_dir
output_path = args.output_dir

# read in the homolog.faa file and process
## initialize dictionaries to store the strain and group information using accession as key

strain_dict = {}
group_dict = {}

with open(input_path) as n:
    for line in n:
        if line.startswith(">"):
            header = line.rstrip().lstrip(">")
            strain_id = header.split("|")[0]
            accession_id = header.split("|")[1]
            group_id = header.split("|")[2]
            strain_dict[accession_id] = strain_id
            group_dict[accession_id] = group_id

# write the group data to a .tsv file
with open(output_path, 'w', newline='') as f_output:
    f_output.write("strain\taccession\tgroup\n")
    for accession_id in strain_dict:
        x = strain_dict[accession_id]+"\t"+accession_id+"\t"+group_dict[accession_id]+"\n"
        f_output.write(x)